title: My Project Documentation   # Your site title
theme: just-the-docs

# Markdown processor
markdown: kramdown

# Enable math with MathJax
kramdown:
  math_engine: mathjax
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Just the Docs settings (optional)
just_the_docs:
  # Enable sidebar navigation on mobile
  show_sidebar_on_mobile: true
  # Navigation options here...
include:
  - _includes/head-custom.html

nav:
  - Home: index.md
  - About: about.md
  - Folder:
      - "Subpage 1": folder/subpage1.md
      - "Subpage 2": folder/subpage2.md
