title: My Project Docs
theme: "just-the-docs"
markdown: kramdown

kramdown:
  math_engine: mathjax
  syntax_highlighter_opts:
    disable : true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Enable mathjax
mathjax:
  enable: true
